version: '3'
services:
  react-app:
    build:
      context: .
      target: runner
      args:
        API_BASE_URL: http://localhost:4000/
        API_DICTIONARY_URL: https://api.dictionaryapi.dev/api/v2/entries/en/
        API_KEY_GIPHY: Iyn6YU9SG7uu1v2BHm7NR7L1gZQH5dOu
        API_GIPHY_GIF: https://api.giphy.com/v1/gifs
        API_GIPHY_STICKER: https://api.giphy.com/v1/stickers
        API_GIPHY_GIF_TRENDING: https://api.giphy.com/v1/gifs/trending
        API_GIPHY_STICKER_TRENDING: https://api.giphy.com/v1/stickers/trending
    environment:
      TERM: linux
      LANG: "C.UTF-8"
      LOG_ROTATION_DAY: 7
      NODE_ENV: production
    env_file:
      - .env.production.docker
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "2"
    ports:
      - "1111:1111"

