export enum QUERY_KEYS {
  POST_LIST = 'POST_LIST',
  DICTIONARY_SEARCH = 'DICTIONARY_SEARCH',
  TOPIC_LIST = 'TOPIC_LIST',
  CARD_LIST = 'CARD_LIST',
  WORD_CHECK = 'WORD_CHECK',
  MESSAGE_LIST = 'MESSAGE_LIST',
  GIF_LIST = 'GIF_LIST',
  GIF_TREND_LIST = 'GIF_TREND_LIST',
  USER_RANDOM_CHECK = 'USER_RANDOM_CHECK',
  WORD_TEST = 'WORD_TEST',
  EARLIEST_POST_LIST = 'EARLIEST_POST_LIST',
}
